### ISSUE TITLE
Use pytest.parametrize for reciprocal

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#107]
## Description
For the moment there are two ways in which the reciprocal is implemented: `nr` (Newton-Raphson) and `log`.
Use `pytest.parametrize` to specify the method.

## Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by danielorihuela** [comment]
Hi @gmuraru, I started working on that. I though I would solve it easy, but I got an error on the pre-commit/action@v2.0.0 python-tests (3.7). Locally, tests seems to work fine. Did my code provoke that error?

Thanks.
