### ISSUE TITLE
Fix darglint errors in tests

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/SyMPC#131]
## Where?
We still have some darglint errors in **tests** files which needs to be fixed.
Also make make darglint check in  GitHub Actions **mandatory** (currently we ignore errors).

## How to check
Make sure you have darglint installed, do

`$ darglint tests`

You will see following errors
![Screenshot 2021-04-28 at 11 20 30 PM](https://user-images.githubusercontent.com/28955148/116449921-54f7cd00-a878-11eb-9355-d79aeecfabee.png)

## Additional Context
Make sure you complete both of the tasks 😄

- [ ] Fix darglint errors.
- [ ] Make darglint mandatory in GitHub Actions.

**Comment by jmaunon** [comment]
@aanurraj , regarding darglint, what I have seen is that it actually checked in GA (without ignoring errors) in modified files (ignoring test folder as well)

Later, at the end of the GA, it is again checked in `src` and `test folder` (ignoring errors in this case)

**Comment by dnabanita7** [comment]
I want to try this.

**Comment by aanurraj** [comment]
> @aanurraj , regarding darglint, what I have seen is that it actually checked in GA (without ignoring errors) in modified files (ignoring test folder as well)
> 
> Later, at the end of the GA, it is again checked in `src` and `test folder` (ignoring errors in this case)

Yes, @jmaunon  I had a conversation with @gmuraru  it would be better if we skip tests. Also I figured out since we have darglint in pre-commit hook, will it be necessary to have a separate action for it ? @gmuraru your views ?

**Comment by jmaunon** [comment]
@aanurraj Yep. It seems is almost duplicated. As you say I would remove the last `darglint` check because is already included in `pre-commit`

**Comment by aanurraj** [comment]
> @aanurraj Yep. It seems is almost duplicated. As you say I would remove the last `darglint` check because is already included in `pre-commit`

Thanks that would work 😬

**Comment by aanurraj** [comment]
> I want to try this.

Hi @dnabanita7 appreciate your help, but there is not much to do in here (initially I thought there was)  may be you can grab some other issue ?

**Comment by dnabanita7** [comment]
ya.. i see..

**Comment by gmuraru** [comment]
So, should we convert this ticket to only skipping the tests from the test folder?
Also, we have darling (to block the PR) in the pre-commit, right? or should we add it there? ( @jmaunon)

**Comment by jmaunon** [comment]
Hi. Yes, I would say that the only this is needed is to remove

https://github.com/OpenMined/SyMPC/blob/7561dec407b230767b9dc517553ea77481d891e9/.github/workflows/tests.yml#L76

because is already checked (without ignoring errors) here:

https://github.com/OpenMined/SyMPC/blob/7561dec407b230767b9dc517553ea77481d891e9/.github/workflows/tests.yml#L64
