### ISSUE TITLE
Check warnings flake

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#14]
## Description
There is a big list of warning which we ignore and we might need some of those

**Comment by arturomf94** [comment]
This is a good point. In general, though, would we not want to keep this in line with the general development of Syft? :thinking: Are there any style guidelines there at the moment?

**Comment by gmuraru** [comment]
Hmm - they have it [here](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)

**Comment by danielorihuela** [comment]
I guess we want to make our flake8 configuration comply with pysyft flake8 configuration, right?

This configuration in particular.
https://github.com/OpenMined/PySyft/blob/8893938264674f0f526b6788fe55e8062a264b8d/setup.cfg#L134

**Comment by gmuraru** [comment]
I think we can have our own -- without the excludes :D
