### ISSUE TITLE
Replicated Sharing Tensor 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/SyMPC#145]
## Feature Description
Currently, MPCTensor performs operations when every party has a single share. We need a Tensor type that supports multiple shares per party to support Falcon Protocol. This issue is to initialize the RSS class with shares distribution and reconstruction. 

## Additional Context
[Falcon Paper](https://arxiv.org/abs/2004.02229)

**Comment by kamathhrishi** [comment]
I would also like to take this issue up.

**Comment by gmuraru** [comment]
Could you split this up in more issues! Like implement Add, Sub, Mul, MatMul, etc?

**Comment by kamathhrishi** [comment]
> Could you split this up into more issues! eg implement Add, Sub, Mul, MatMul, etc for RSS?
> And make this ticket only: add stub for `ReplicatedSharingTensor`

Yeah sure. that's a good idea.

**Comment by kamathhrishi** [comment]
@gmuraru I have created separate issues for the same. You can add it to RSS Tensor Milestone.
