### ISSUE TITLE
Falcon Primitive Operations 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/SyMPC#146]
## Feature Description
Primitive operations of Falcon Protocol:

- [x] Addition with public value 
- [x] Subtraction with public value 
- [x] Addition with another secret 
- [x] Subtraction with public value
- [x] Multiplication with public value 
- [x] Multiplication with another secret 

## Additional Context
[Falcon Paper](https://arxiv.org/abs/2004.02229)
This PR has a dependency on #145 and should be built on Replicated Secret Share Tensor.

**Comment by gmuraru** [comment]
I think this could also be split into multiple issues?
