### ISSUE TITLE
Move allowlist from Syft to SyMPC

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#155]
## What?
Currently, we have a dependency for running tests because we might require some functionality from Syft. One of those is the list of allowed operations we can run on a `ShareTensor` -- they are added in ```alowlist``` in (```src/syft/lib/sympc/__init__.py```).

When we add a new operation to the `SharingTensor` and want to call that operation remotely, we need to add it to that allowlist (this requires 2 PRs in 2 repositories).

Move the allowlist into our repository and make Syft only import it.

## Why?
By moving the allowlist into our repo, we decouple this logic from Syft and SyMPC.

**Comment by danielorihuela** [comment]
This should be closed.

**Comment by gmuraru** [comment]
Done
