### ISSUE TITLE
Create a better README.md

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#16]

**Comment by danielorihuela** [comment]
Since I am doind the contribution readme I think it may be a good idea that I take up this issue too. Could you explain a little bit more what exactly do you wanna put on the readme? Or I can feel free to do whatever I feel like doing?

**Comment by jmaunon** [comment]
> Since I am doing the contribution readme I think it may be a good idea that I take up this issue too. Could you explain a little bit more what exactly do you wanna put on the readme? Or I can feel free to do whatever I feel like doing?

Hi @danielorihuela . I have been talking about this with Rasswanth becuase this Readme should be well-documented and should work as main page of the sphinx documentaiton. Please, just talk to him to be aligned

If you need help, just let me know.

**Comment by danielorihuela** [comment]
Perfect
