### ISSUE TITLE
Adding synk and safety to CI

### ISSUE THREAD

**Issue by Param-29** [OpenMined/SyMPC#165]
## Feature Description
Similar to this issue: https://github.com/OpenMined/PySyft/issues/5448

## Is your feature request related to a problem?
Suggested by security team 

## Additional Context
I'd like to work on this issue.

**Comment by Param-29** [comment]
PR merged, this issue can be closed!

**Comment by gmuraru** [comment]
This was reverted because it broke `main`

**Comment by Syzygianinfern0** [comment]
@gmuraru we can close this right?

With regard to https://github.com/OpenMined/SyMPC/commit/79b51c5f677e4f0537f1cf5c4cfd72c35d0fad51

**Comment by gmuraru** [comment]
Ahh..Yes!
