### ISSUE TITLE
Fix inference benchmark

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/SyMPC#168]
## Description
We have a benchmark [here](https://github.com/OpenMined/SyMPC/blob/main/benchmarks/module/module_benchmark_test.py), the issue we are currently benchmarking whole function but we want to benchmark just the inference.

## Additional Context
for more info ping me (@Anubhav) on slack.

**Comment by libratiger** [comment]
I can do this, but can you provide more information, which test is the inference?

**Comment by aanurraj** [comment]
Sure @libratiger if you go [here](https://github.com/OpenMined/SyMPC/blob/63cf891cd91634b4c049dea12d9c28eece7d60ad/benchmarks/module/conv_model.py#L74) that particular line is the inference we want to benchmark that particular line, not the whole function.

**Comment by libratiger** [comment]
Ok， I will submit a PR soon

**Comment by libratiger** [comment]
I just add the PR
