### ISSUE TITLE
Add `reduction` param to mse_loss

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#176]
## Description
Currently, we default (and only do) the `sum` reduction method. We should also add the average one.

## Are you interested in working on this improvement yourself?
- Yes, I am.
- 
## Additional Context
A test should be added to validate the behavior.

**Comment by libratiger** [comment]
Can you provide more information? so I can help on this issues

**Comment by gmuraru** [comment]
For the moment we default to the `sum` reduction operation when doing the `mse_loss`. Ideally, we would want to have a parameter to select if we want `sum` or `avg` . This is dependent on another PR for training :D

**Comment by gmuraru** [comment]
Is is merged now :D - the function is `mse_loss`

**Comment by libratiger** [comment]
I see. I will work on this issue

**Comment by gmuraru** [comment]
Added you to the issue

**Comment by libratiger** [comment]
I just add one PR, please review it @gmuraru

**Comment by gmuraru** [comment]
This si done in [here](https://github.com/OpenMined/SyMPC/pull/180)
