### ISSUE TITLE
Add Roadmap in the README.md?

### ISSUE THREAD

**Issue by libratiger** [OpenMined/SyMPC#192]
## Description
A roadmap maybe better to guide new contributor

**Comment by gmuraru** [comment]
There is already a `Contributing.MD` file. We could enhance that if you think it needs more information

**Comment by libratiger** [comment]
Yes. the contributing.MD is very detailed.
I see there is some PR about the FALCON protocol or the ABY protocol, so is there any plan for the direction of our repo?
