### ISSUE TITLE
Add yaml configuration for CodeCov

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/SyMPC#214]
## Description
We currently support codecov, since it requires a YAML configuration file more about this YAML configuration can be found [here](https://docs.codecov.io/docs/codecov-yaml).
For any more clarification/question ping @gmuraru or me on slack.

**Comment by shubhank-saxena** [comment]
Hello @aanurraj ! I am new to SyMPC and would love to take on this issue if it's available for grabs! Thank you

**Comment by aanurraj** [comment]
@shubhank-saxena yes sure 😃
