### ISSUE TITLE
Flaky test_max_multiple_max  unit test 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/SyMPC#233]
## Description
The unit test _tests/sympc/tensor/static_test.py::test_max_multiple_max_ is flaky. That is the test randomly fails, making authors of Pull requests have unit tests fail irrespective of the changes made to the codebase. 
An example of it failing: https://github.com/OpenMined/SyMPC/runs/2789594398 

## Expected Behavior
The test should pass all the time when the expected behaviour is met and fail otherwise.

**Comment by hershd23** [comment]
Let me know if this issue is still available.

**Comment by rasswanth-s** [comment]
Sure @hershd23 go for it 👍

**Comment by hershd23** [comment]
@rasswanth-s can you give me some details on how to replicate it?

**Comment by rasswanth-s** [comment]
You could run the test a number of times,it would surely be mix of pass and fails.
https://github.com/OpenMined/SyMPC/blob/ff18bf4ebc41214aa573b730c1b8ad9568795407/tests/sympc/tensor/static_test.py#L64
You could also use `pytest-repeat`
Add a decorator at the top `pytest.mark.repeat(n)` a suitable number n.

**Comment by hershd23** [comment]
```
tests/sympc/tensor/static_test.py::test_max_multiple_max[44-50] PASSED                                                           [ 88%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[45-50] PASSED                                                           [ 90%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[46-50] PASSED                                                           [ 92%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[47-50] PASSED                                                           [ 94%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[48-50] PASSED                                                           [ 96%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[49-50] PASSED                                                           [ 98%]
tests/sympc/tensor/static_test.py::test_max_multiple_max[50-50] PASSED                                                           [100%]
```

Ran the test 50 times, passed 50 times. Not able to replicate the error.

I am currently using WSL, Python 3.9 to test, but the spec it errored out on was MacOS Python 3.8. But still I don't think that a different OS/Python version could resulted in an error.

**Comment by rasswanth-s** [comment]
It should have resulted in a error.Could you use the `pytest-repeat` and mark the test order:
`pytest.mark.order(1)` run in your local Github Actions CI ,by pushing to your local branch and check.

**Comment by kamathhrishi** [comment]
@rasswanth-s Does this error still occur in Github CI? It's been very long I got it.

**Comment by rasswanth-s** [comment]
Yes @kamathhrishi ,the test did not fail in the current CI runs.Maybe we could run this test sufficiently large number of times and test it in the CI .

**Comment by hershd23** [comment]
@kamathhrishi @rasswanth-s is there anything more to do for this test?

> `pytest.mark.order(1)` run in your local Github Actions CI ,by pushing to your local branch and check.

Not familiar with Github actions CI. So if this needs to be done could you detail the steps that have to be done.

**Comment by rasswanth-s** [comment]
Sure , could you ping me on Slack, my handle: `@Rasswanth`

**Comment by hershd23** [comment]
@rasswanth-s @kamathhrishi 
Have a look at this. All test-max-multiple-max pass. However a different test is failing.

https://github.com/hershd23/SyMPC/runs/3193588890

**Comment by rasswanth-s** [comment]
Its good that test_max_multiple_max is not flaky, not sure, how it was fixed automatically. @hershd23 great job on identifying it .If you are interested there are several other flaky issues, if you could work on one of them,which would greatly improve SyMPC CI.I think we could close the issue @kamathhrishi  @gmuraru .

**Comment by rasswanth-s** [comment]
I think after @gmuraru  , @kamathhrishi  ,looks at the test results ,@hershd23  could you do a quick PR, for removing the order from `test_max_multiple_max` and changing the subsequent order correspondingly,

**Comment by hershd23** [comment]
> I think after @gmuraru , @kamathhrishi ,looks at the test results ,@hershd23 could you do a quick PR, for removing the order from `test_max_multiple_max` and changing the subsequent order correspondingly,

@rasswanth-s I didn't get your point clearly. I'll try to write what I understood correct me if I am wrong
So the idea is the remove the order from `test_max_multiple_max` and adjust the orders of other tests by 1.
Also if I got you right, why is this change required?

**Comment by rasswanth-s** [comment]
Sure,Since some of the tests are flaky, usually the whole test suite runs,(which takes around an hour) and the CI fails, We kept ordering for the flaky tests , so that It would fail first and the result would be known at the start,so we could restart the tests soon.Did I answer you question.

**Comment by rasswanth-s** [comment]
I think there are around 12 flaky test with the order marked right now in the test suite.

**Comment by hershd23** [comment]
Ah right, I didn't know the all those tests were flaky too. I was just wondering why would you need me to change test orders only. Got it. Will make a PR soon

**Comment by rasswanth-s** [comment]
Good Catch :+1: .I think it would be ,good to have the flaky tests ordered sequentially, could you also modify the `pytest.mark.order(14)` to have sequential number accordingly

**Comment by rasswanth-s** [comment]
close by #289
