### ISSUE TITLE
Modification of CI to run scheduled tests.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/SyMPC#244]
## Description
Our current CI  runs all the test suite, which makes it slow.We would ideally want to run limited number of github runners,similar like PySyft which runs only latest versions of python for its tests,and to also integrate scheduled CI tests everyday which runs the whole test suite.This would greatly improve our CI.

## Additional Context
Syft PR Tests : [PR_Tests](https://github.com/OpenMined/PySyft/blob/dev/.github/workflows/syft-pr_tests.yml)
Schduled Tests : [Scheduled_Tests](https://github.com/OpenMined/PySyft/blob/dev/.github/workflows/syft-version_tests.yml)

**Comment by danielorihuela** [comment]
I am interested in collaborating with you @rasswanth-s on this.

**Comment by danielorihuela** [comment]
@rasswanth-s I have made the changes we talked about. Check them when you can.
