### ISSUE TITLE
Add a CODEOWNERS file

### ISSUE THREAD

**Issue by arturomf94** [OpenMined/SyMPC#25]
## Description
It'd be nice to have a CODEOWNERS file so as to set automatic assignments for reviews and have more control over the status checks in PRs.

## Additional Context
This was something used in `syft_0.2.x` and it was usefult IMO.

**Comment by theAkhileshRai** [comment]
Hey George, I'll be taking this up.

**Comment by theAkhileshRai** [comment]
Thanks working on this!

**Comment by gmuraru** [comment]
Hey @theAkhileshRai are you still working on this?

**Comment by shubhank-saxena** [comment]
Hello @gmuraru . I would like to take on this issue!
