### ISSUE TITLE
Add Approximations

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#26]
## Feature Description
 - Create a new folder where we keep the approximations for our different functions (check syft_0.2.x)
 - Add tests for those approximations

## Is your feature request related to a problem?
- Have approximations for non-linear functions
- 
## Additional Context
- We need to have a way to approximate non-linearities
- Having more approximations methods to compute a non-linearity would allow flexibility depending on a user needs

**Comment by gmuraru** [comment]
@aanurraj you were working on this, right?

**Comment by aanurraj** [comment]
> @aanurraj you were working on this, right?
Yes :)
