### ISSUE TITLE
CodeCov - show on PR

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#267]
## Description
CodeCov shows the code coverage for the tests when we do a merge, but ideally, we would want to have a comment on the PR.
Also, codecov should only be run, but without failing (have the red X) on the main branch.

## Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by shubhank-saxena** [comment]
Hello @gmuraru . I am new to the community and would love to pick up this issue!
