### ISSUE TITLE
A question about PySyft/packages/syft/examples/secure-multi-party-computation/Duet/1-DS-1-DO

### ISSUE THREAD

**Issue by Blogg9ggg** [OpenMined/SyMPC#279]
## Question
I'm trying to run this example, but the program reports an error that `The session could not be found` when I print the `(x + y).reconstruct()`.

## Further Information
```
[2021-07-16T00:34:16.473948-0400][CRITICAL][logger]][26631] The session e2b1f5cf-6c06-4e8e-8268-b3c13c729275 could not be found
Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ot be found')>) at /home/student02/anaconda3/envs/llj/lib/python3.9/site-packages/pyee/_asyncio.py:55
......
  File "/home/student02/anaconda3/envs/llj/lib/python3.9/site-packages/syft/lib/sympc/share.py", line 48, in proto2object
    raise ValueError(f"The session {proto.session_uuid} could not be found")
ValueError: The session e2b1f5cf-6c06-4e8e-8268-b3c13c729275 could not be found
```

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Linux
 - OS Version: Linux version 4.15.0-76-generic (buildd@lcy01-amd64-029) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))
 - Language Version: Python 3.9.5
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by rasswanth-s** [comment]
Hi @Blogg9ggg ,
    The SyMPC examples in Pysyft are broken https://github.com/OpenMined/PySyft/issues/5771, an issue is also created for it.We are working on solving it. You could try this SyMPC examples https://github.com/OpenMined/SyMPC/tree/main/examples

**Comment by Blogg9ggg** [comment]
@rasswanth-s Thank you so much.

**Comment by jiyanxin** [comment]
I have a same problem,  is there a remote available examples?

**Comment by rasswanth-s** [comment]
The SyMPC codebase underwent a lot of changes, we would have to update the remote examples in PySyft.

**Comment by jiyanxin** [comment]
The example of remote MPC PySyft/packages/syft/examples/secure-multi-party-computation/Duet/1-DS-1-DO, if I want to run it without bugs, which version of syft and sympc I should install ?

**Comment by jiyanxin** [comment]
> The SyMPC codebase underwent a lot of changes, we would have to update the remote examples in PySyft.

The example of remote MPC PySyft/packages/syft/examples/secure-multi-party-computation/Duet/1-DS-1-DO, if I want to run it without bugs, which version of syft and sympc I should install ?
