### ISSUE TITLE
Session Tests

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#39]
## Description
Add tests such that the ```Session``` class has 100% coverage.

The session class can be found in ```src/sympc/session/session.py``` and the tests should be added in the ```tests``` folder

**Comment by arturomf94** [comment]
I'll take this up :)

**Comment by arturomf94** [comment]
I guess we should probably get https://github.com/OpenMined/SyMPC/issues/36 done first? What do you think?

**Comment by gmuraru** [comment]
Yep! Ideally, we would do that first and then this, but we can also do this and then that! (and we simply split the tests between ```Session``` and ```SessionManager```)
