### ISSUE TITLE
Add the matmul operation to Duet tutorial

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#43]
## Description
In the [Syft repo - branch ```0.4```](https://github.com/OpenMined/PySyft/tree/0.4) there are multiple tutorials involving SMPC.
The ones involving showcase [VMs](https://github.com/OpenMined/PySyft/tree/0.4/examples/secure-multi-party-computation/VMs)  the ```matmul``` operation, but we should also add it to the [Duet notebooks](https://github.com/OpenMined/PySyft/tree/0.4/examples/secure-multi-party-computation/Duet).

Add an example where we use ```matmul``` in both scenarios:
 - with 1 Data Scientist (DS) and 1 Data Owner (DO)
 - with 1 Data Scientist (DS) and 2 Data Owners (DOs)

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
To use SyMPC you also need to have installed Syft.

**Comment by jmaunon** [comment]
I'll take this up :)

**Comment by gmuraru** [comment]
Great!

**Comment by jmaunon** [comment]
See https://github.com/OpenMined/PySyft/pull/5020

**Comment by gmuraru** [comment]
This is done ^^ Thank you
