### ISSUE TITLE
MPC generate_shares simple tensor

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#46]
## What?
The MPC Tensor ```generate_shares``` method currently takes as secret a ```ShareTensor```, but it should also be able to a tensor + specify the precision (see the discussion [here](https://github.com/OpenMined/SyMPC/pull/40#discussion_r553579902)

## Why?
Would simplify the API.

**Comment by jmaunon** [comment]
I can take a look!

**Comment by gmuraru** [comment]
Thank you! I assigned it to you -- if you have any question just ping me on slack
