### ISSUE TITLE
Allow python3.6 or add requirement for python 3.7

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#47]
## Feature Description
Allow support for ```python3.6``` or add a requirement in the ```setup.cfg``` file such that we require ```python3.7``` to run SyMPC.
The problem is that in the ```utils.py``` file we use:
```
with Executor(
            max_workers=nr_parties, initializer=initializer, initargs=(loop,)
        ) as executor
```

and the ```initializer``` argument is specific to ```python``` version ```>=3.7```.

If we want to add support for ```3.6``` we would need to refactor it.

## Is your feature request related to a problem?
Yes.
If a user installs SyMPC they would not be able to use it with python3.6.

**Comment by cyborg1995** [comment]
Hi! I would like to take this up!

**Comment by cyborg1995** [comment]
Hi! I would like to take this up!

**Comment by gmuraru** [comment]
All yours! :D

**Comment by gmuraru** [comment]
Dropping support for python3.6 since PySyft also dropped support for it
