### ISSUE TITLE
Replace MPCTensor.generate_shares

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/SyMPC#50]
## What?
Replace all the instances where we use:
```
shares = MPCTensor.generate_shares()
```
with 

```
shares = MPCTensor.generate_shares(data, ...)
```

See [this PR](https://github.com/OpenMined/SyMPC/pull/48#pullrequestreview-576167358) for more detail.

## Why?
Simplify the api and reduce repetitve patterns..

## Breakdown
It is not neccesaty to breakdown, however it is necessary to refactor (at least) the following module: `protocol/beaver/beaver.py`

## Additional Context
Wait until #48 is merged.

**Comment by jmaunon** [comment]
assign to my self

**Comment by LaRiffle** [comment]
Hey @jmaunon! Is this issue closed? I see you have a linked PR :)

**Comment by jmaunon** [comment]
@LaRiffle , not exactly. In the [PR](https://github.com/OpenMined/SyMPC/pull/48#pullrequestreview-576167358) I updated the `MPCTensor` class in order to avoide repetitive patterns, but should be applied to a couple of files. 
I have seen you already assigned to me, so I will take a I look and I will submit a new PR or I will comment this issue in order to close it.

**Comment by jmaunon** [comment]
I have already submitted a PR #57
