### ISSUE TITLE
Add Support for Torch Module

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/SyMPC#55]
## Description
We want to support encrypted inference over casual pytorch models, we need to support basic layers such as
- nn.Linear
- nn.ReLU
- nn.Conv2d

to be applied on our MPC tensors

## How?
This needs to be done in colab with the syft core team to make sure our abstraction is correct and compliant with them

## Breakdown
- Make a pseudo code demo of nn.Linear support and discuss this with the SyMPC + Syft Core teams #67
- Implement nn.Linear with support of MPC + tests #68
- Implement nn.ReLU with support of MPC  + tests
- Implement nn.Conv2d with support of MPC  + tests

## Who else?
@OpenMined/syft-core
@OpenMined/cryptography

**Comment by gmuraru** [comment]
@LaRiffle I think a good first step is to support linear layers + ReLu? and after this start adding the Conv2D?

**Comment by gmuraru** [comment]
I think a good first step for this would be to add the a ```share``` and a ```reconstruct``` method at the level of the [Syft Module](https://github.com/OpenMined/PySyft/blob/dev/src/syft/lib/torch/module.py).

The ```share``` method would simply call share on the parameters for each layer and ```reconstruct``` would rebuild them

**Comment by arturomf94** [comment]
Hey! I think this is the issue @gmuraru was referring to during our last meeting... I'm willing to take a stab at it :hocho: 

However I noticed there are a couple of minor issues in the same milestone that might need fixing first: 

1. https://github.com/OpenMined/SyMPC/issues/61
2. https://github.com/OpenMined/SyMPC/issues/62

What do you think? Should I solve these first?

**Comment by arturomf94** [comment]
#61 seems easy enough so I'm already tackling it with #65 :+1:

**Comment by gmuraru** [comment]
This is done!
 - Used SyftModule as an already structure for our modules
 - Added the `share` and `reconstruct` methods to the SyftModule
 - Replace the `torch_ref` attribute (this is used for non-linearities like ReLu) from `SyftModule` with our own implementations
 - The share process would share the ```state_dict``` and replace each torch layer with out implementation (for the moment we have only ```Conv2d``` and ```Linear```)
 - The reconstruct process would reconstruct the ```state_dict``` (that was shared) and replace our layers with the torch ones
