### ISSUE TITLE
SyftCore parity doc linter

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#60]
## Description
Add a doc linter in the github ```workflows``` as the one that already exists in Syft Core added in [this PR](https://github.com/OpenMined/PySyft/commit/73a02de786948c4821cd1eb177f6f106fdf80ac6).

## Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by jmaunon** [comment]
@gmuraru assign to me, I will take a look
