### ISSUE TITLE
Multiplying more then 2 MPC Tensors together gives error

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/SyMPC#63]
## Description

Multiplying more than 2 MPC Tensors together gives error, either be it same or 3 different tensors it still produces error. 

## How to Reproduce
![Screenshot 2021-02-27 at 11 24 42 PM](https://user-images.githubusercontent.com/28955148/109395555-f9ca5c80-7952-11eb-8059-3d9c72806ae5.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by gmuraru** [comment]
This is fixed
