### ISSUE TITLE
Add "share" showcase to the introduction tutorial

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#71]
## Description
We can call ```share``` on a ```torch.tensor```. The method will return an ```MPCTensor```.
Showcase this usage in the introductory tutorial since it is more intuitive for the normal user.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
The tutorial can be found [here](https://github.com/OpenMined/SyMPC/blob/main/examples/introduction.ipynb)

**Comment by jmaunon** [comment]
@gmuraru please, assign to me. I have already submitted a PR.
(Call `.share` directly from a `torch.Tensor` instead of a `MPCTensor` makes the code more understable, congrats!)
