### ISSUE TITLE
Add "*.txt" files as a path to trigger the GH workflow

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#72]
## Description
Currently, if we change only the ```requirements``` files we would not trigger the tests.
Add the ```**.txt``` as a ```path``` in the GH workflow actions. 

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
This will allow us to test different versions of the package we use directly in the CI.

**Comment by RaghavPrabhakar66** [comment]
Hi, I would love to contribute to this issue.

**Comment by RaghavPrabhakar66** [comment]
@gmuraru there is already `requirements*.txt` added to path in tutorials.yml, so is there a need to add `**.txt` to that?

**Comment by gmuraru** [comment]
Yep - we should also add it to the ```tests``` requirement.

**Comment by gmuraru** [comment]
Solved
