### ISSUE TITLE
Sort a list of MPCTensors

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#92]
## Feature Description
Create a ```sort``` function in the ```utils``` folder to sort in increasing or decreasing order a list of ```MPCTensor```.

## Is your feature request related to a problem?
The possibility to sort a list of `MPCTensors`.

**Comment by Pratyaksh7** [comment]
I am new to this. could you help me to contribute for this repository.. I am having strong command over python language but new to open source world. If you can provide me guidance that will be really appreciated.

**Comment by gmuraru** [comment]
Hello! Some good first steps would:
1. Install SyMPC along Syft and run the examples (in this way you make sure you have the proper setup)
2. Implement the sorting using the already implemented Private Compare operation

If you have any more questions you can post messages here or join the Slack channel (the link can be found in the README.md)

**Comment by Pratyaksh7** [comment]
Here I just checked for the slack channel link.. but its not available in the README.md file

**Comment by gmuraru** [comment]
Near the title, there is an icon with "Chat on Slack"

**Comment by Pratyaksh7** [comment]
Could you tell the channel name. I dont know why there is some issue in joining the slack channel from that link in the README.md file

**Comment by gmuraru** [comment]
The slack channel name is: `openmined.slack.com`

**Comment by Pratyaksh7** [comment]
there's again channel issue
Can you invite me to your channel? email: pratyakshgupta7@gmail.com

**Comment by kamathhrishi** [comment]
@gmuraru I have written an implementation of this. Can you assign me?

**Comment by gmuraru** [comment]
Sure!
