### ISSUE TITLE
Replace torch.allclose from tests

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#93]
## Description
We want to be framework agnostic (even if currently we are highly coupled with `torch`).
For this we should remove all `torch` specific functions from the files where there should be "generic"-like code.

One of those functions is ```allclose``` from `torch`.
This issue is to reove the `allclose` function from the test files.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
Check if `pytest` has an ```allclose``` function or check what other libraries (more general than `torch`) are doing this.

**Comment by linamnt** [comment]
Hi, I could do this. It seems other instances use `np.allclose`, is this sufficient or would you also want to use the pytest api for those cases too? If so, there is the `approx` function from pytest: https://docs.pytest.org/en/latest/reference/reference.html?highlight=approx#pytest.approx

**Comment by gmuraru** [comment]
I think the ```approx``` would be great!
